from typing import Any
from PyQt5.QtWidgets import QWidget


class Globals:
    def globals(self, name: Any, value: Any) -> None:  ...
    def getGlobals(self, name: Any) -> Any:  ...
    def delGlobals(self, name: Any) -> None:  ...

class Default:
    @staticmethod
    def string(v: str) -> Any: ...
    @staticmethod
    def onClicked(widget_value: Any, widget: QWidget, value: Any = None) -> None: ...
